# =============================================================================
# ОБЪЕДИНЕННАЯ КОНФИГУРАЦИЯ SHIWATIME
# =============================================================================
# Этот файл содержит все конфигурации из отдельных YAML файлов:
# - ptpsquared-example.yml
# - shiwatime.yml  
# - test.yml
# - timesource-example.yml
# =============================================================================

# =============================================================================
# ОСНОВНАЯ КОНФИГУРАЦИЯ SHIWATIME
# =============================================================================

shiwatime:
  # =================================================================
  # ЛИЦЕНЗИЯ И КОНФИГУРАЦИЯ
  # =================================================================
  license:
    keyfile: '/etc/timebeat/timebeat.lic'
  
  config:
    peerids: '/etc/timebeat/peerids.json'

  # =================================================================
  # СИНХРОНИЗАЦИЯ ЧАСОВ
  # =================================================================
  clock_sync:
    # По умолчанию true - включена синхронизация часов
    # Установка в false для режима только мониторинга
    adjust_clock: true
    
    # Ограничение на шаг коррекции времени
    step_limit: 15m # "s", "h" "d" можно использовать для обозначения секунд, часов или дней

    # =============================================================
    # ПЕРВИЧНЫЕ ИСТОЧНИКИ ВРЕМЕНИ
    # =============================================================
    primary_clocks:
      
      # =========================================================
      # PTP+Squared как основной источник времени
      # =========================================================
      - type: ptpsquared
        interface: eth0
        domains: [115, 116]
        seats_to_offer: 4
        seats_to_fill: 3
        concurrent_sources: 1
        capabilities: ["hqosc-1500"]
        preference_score: 0
        reservations: ["1500:50%:115,116", "750:25%"]
        group: ptpsquared_primary
        logsource: 'PTP+Squared Primary'

      # =========================================================
      # NTP как основной источник времени
      # =========================================================
      - protocol: ntp
        ip: '0.pool.ntp.org'
        pollinterval: 4s
        monitor_only: false

      # =========================================================
      # TimeSource конфигурации
      # =========================================================
      - type: "timesource"
        host: "192.168.1.100"
        port: 123
        weight: 10
        timesource_type: "ntp"
        timesource_mode: "client"
        timesource_config:
          polling_interval: 64
          max_offset: "1000ms"
          max_delay: "100ms"
          trust: true
        polling_interval: 64
        max_offset: 1000
        max_delay: 100
        trust: true
        
      - type: "timesource"
        interface: "eth0"
        weight: 8
        timesource_type: "ptp"
        timesource_mode: "slave"
        timesource_config:
          domain: 0
          transport_type: "UDPv4"
          log_announce_interval: 1
          log_sync_interval: 0
          log_delay_req_interval: 0
        domain: 0
        transport_type: "UDPv4"
        log_announce_interval: 1
        log_sync_interval: 0
        log_delay_req_interval: 0
        
      - type: "timesource"
        device: "/dev/ttyUSB0"
        weight: 6
        timesource_type: "nmea"
        timesource_mode: "gps"
        timesource_config:
          baud_rate: 9600
          data_bits: 8
          stop_bits: 1
          parity: "none"
        baud_rate: 9600
        data_bits: 8
        stop_bits: 1
        parity: "none"
        
      - type: "timesource"
        device: "/dev/pps0"
        weight: 5
        timesource_type: "pps"
        timesource_mode: "input"
        timesource_config:
          pps_mode: "rising"
          pps_kernel: true
        pps_mode: "rising"
        pps_kernel: true
        
      - type: "timesource"
        interface: "eth0"
        weight: 4
        timesource_type: "phc"
        timesource_mode: "slave"
        timesource_config:
          phc_index: 0
          hw_timestamping: true
        phc_index: 0

    # =============================================================
    # ВТОРИЧНЫЕ ИСТОЧНИКИ ВРЕМЕНИ (активируются при отсутствии первичных)
    # =============================================================
    secondary_clocks:
      
      # =========================================================
      # Резервные NTP серверы
      # =========================================================
      - type: ntp
        host: 'pool.ntp.org'
        port: 123
        polling_interval: 4s
        group: ntp_backup
        logsource: 'NTP Backup'
      
      - protocol: ntp
        ip: '2.pool.ntp.org'
        pollinterval: 4s
        monitor_only: false

      # =========================================================
      # PTP резервный источник
      # =========================================================
      - type: ptp
        interface: eth0
        domain: 0
        profile: 'G.8275.2'
        group: ptp_backup
        logsource: 'PTP Backup'

      # =========================================================
      # TimeSource резервные конфигурации
      # =========================================================
      - type: "timesource"
        host: "pool.ntp.org"
        port: 123
        weight: 3
        timesource_type: "ntp"
        timesource_mode: "client"
        timesource_config:
          polling_interval: 128
          max_offset: "2000ms"
          max_delay: "200ms"
        polling_interval: 128
        max_offset: 2000
        max_delay: 200
        
      - type: "timesource"
        weight: 2
        timesource_type: "mock"
        timesource_mode: "test"
        timesource_config:
          offset: "10ms"
          jitter: "5ms"
          quality: 100
        options:
          offset: "10ms"
          jitter: "5ms"
          quality: "100"

  # =================================================================
  # НАСТРОЙКИ ТОНКОЙ НАСТРОЙКИ PTP
  # =================================================================
  ptp_tuning:
    # Включить глобальные PTP сокеты
    enable_ptp_global_sockets: true
    
    # Случайная задержка DELAY_REQ пакетов на 200-800мс
    relax_delay_requests: true
    
    # Автоматическое обнаружение PTP источников
    auto_discover_enabled: true
    
    # TTL для PTP multicast
    multicast_ttl: 1
    
    # DSCP настройки для PTP сообщений
    dscp:
      general: "CS6"
      event: "CS7"
    
    # Стандарт PTP
    ptp_standard: "IEEE 1588-2008"
    
    # Качество часов
    clock_quality:
      auto: true
      class: 248
      accuracy: "0xFE"
      variance: "0xFFFF"
      timesource: "0xA0"
    
    # PHC настройки
    phc:
      phc_offset_strategy: ["auto"]
      phc_local_pref: ["auto"]
      smoothing_strategy: ["auto"]
      phc_lp_filter_enabled: true
      phc_ng_filter_enabled: true
      phc_samples: ["auto"]
      phc_one_step: ["auto"]
      tai_offset: "37"
      phc_offsets: ["auto"]
      pps_config: ["auto"]

  # =================================================================
  # СИНХРОНИЗАЦИЯ RTC
  # =================================================================
  synchronise_rtc:
    enable: true
    clock_interval: 11m

  # =================================================================
  # КОНФИГУРАЦИЯ PTP+Squared
  # =================================================================
  ptpsquared:
    enable: true
    
    # Настройки обнаружения
    discovery:
      mdns: true
      dht: true
      dht_seed_list: 
        - "/ip4/10.101.101.23/tcp/65107/p2p/16Uiu2HAmJiQvJQbja8pf5dKAZsSYxWmcDCxZaoYbMUL5X7GnXej9"
    
    # Управление ключами
    keypath: "/etc/timebeat/ptp2key.private"
    
    # Сетевые настройки
    domains: [115, 116]
    interface: eth0
    
    # Управление емкостью
    seats_to_offer: 5
    seats_to_fill: 3
    concurrent_sources: 10
    
    # Интервалы синхронизации
    active_sync_interval: 1
    active_delayrequest_interval: 1
    monitor_sync_interval: 1
    monitor_delayrequest_interval: 1
    
    # Качество и предпочтения
    capabilities: ["gps", "ptp", "ntp"]
    preference_score: 100
    reservations: []
    
    # Отладка
    debug: false
    
    # Расширенные настройки
    advanced:
      asymmetry_compensation: 0.0
      is_better_factor: 1.0
      eos_weight: 1.0
      base_hop_cost: 1.0
      swts_cost: 1.0
      hwts_cost: 0.5
      latency_analysis_enable: true

  # =================================================================
  # НАСТРОЙКИ CLI
  # =================================================================
  cli:
    enable: true
    bind_port: 65129
    bind_host: "127.0.0.1"
    username: "admin"
    password: "password"

  # =================================================================
  # НАСТРОЙКИ HTTP
  # =================================================================
  http:
    enable: true
    bind_port: 8088
    bind_host: "127.0.0.1"

  # =================================================================
  # НАСТРОЙКИ ЛОГИРОВАНИЯ
  # =================================================================
  logging:
    # Размер буфера для записей при отключении от Elastic
    buffer_size: 1024
    
    # Вывод в stdout
    stdout:
      enable: true
    
    # Удаленный syslog
    syslog:
      enable: false
      host: remote.syslog-server.com
      port: 514

# =============================================================================
# ОБЩИЕ НАСТРОЙКИ
# =============================================================================

# Имя отправителя
name: "shiwatime-host"

# Теги отправителя
tags: ["time-sync", "production", "timesource", "ntp", "ptp", "gps", "pps", "phc"]

# Дополнительные поля
fields:
  env: production
  datacenter: dc1
  environment: "production"
  rack: "rack1"

# =============================================================================
# НАСТРОЙКИ DASHBOARDS И ILM
# =============================================================================
setup:
  dashboards:
    enabled: true
    url: "http://localhost:5601"
    directory: "/usr/share/shiwatime/kibana"
  
  # Настройки ILM (Index Lifecycle Management)
  ilm:
    enabled: true
    policy_name: "shiwatime"
    policy_file: "/etc/shiwatime/ilm_policy.json"
    check_exists: true

# =============================================================================
# НАСТРОЙКИ ВЫВОДА
# =============================================================================

# Настройка вывода в Elasticsearch
output:
  type: "native"
  elasticsearch:
    # Хосты Elasticsearch
    hosts: ['localhost:9200']
    
    # Протокол (http или https)
    protocol: 'http'
    
    # Аутентификация (необязательно)
    #username: 'elastic'
    #password: 'changeme'
    #api_key: 'id:api_key'
    
    # SSL настройки для безопасного соединения
    #ssl.certificate_authorities: ['/etc/shiwatime/pki/ca.crt']
    #ssl.certificate: '/etc/shiwatime/pki/shiwatime.crt'
    #ssl.key: '/etc/shiwatime/pki/shiwatime.key'
    #ssl.verification_mode: "certificate"
    
    # Индекс для Elasticsearch
    index: "shiwatime-%{+yyyy.MM.dd}"
    
    # Шаблон индекса
    template:
      name: "shiwatime"
      pattern: "shiwatime-*"

# =============================================================================
# НАСТРОЙКИ МОНИТОРИНГА
# =============================================================================
monitoring:
  enabled: true
  elasticsearch:
    hosts: ["localhost:9200"]