#              ____    _     _                  _______ _                
#             / ___|  | |__ (_)_      ____ _|__   __(_)_ __ ___   ___ 
#             \___ \  | '_ \| \ \ /\ / / _` | | |  | | | '_ ` _ \ / _ \
#              ___) | | | | | |\ V  V / (_| | | |  | | | | | | | |  __/
#             |____/  |_| |_|_| \_/\_/ \__,_| |_|  |_|_|_| |_| |_|\___|

################### ShiwaTime Configuration #########################

shiwatime:

  # Расположение файла лицензии для премиум функций
  license:
    keyfile: '/etc/shiwatime/shiwatime.lic'

  # Расположение файла конфигурации peer identities
  config:
    peerids: '/etc/shiwatime/peerids.json'

  # Конфигурация синхронизации часов
  clock_sync:

    # По умолчанию true - включена синхронизация часов
    # Установка в false для режима только мониторинга
    adjust_clock: true

    # Ограничение на шаг коррекции времени
    step_limit: 15m # "s", "h" "d" можно использовать для обозначения секунд, часов или дней

    # Первичные источники времени
    primary_clocks:

      # Пример конфигурации NTP
      - protocol: ntp
        ip: '0.pool.ntp.org'
        pollinterval: 4s
        monitor_only: false

      # Пример конфигурации NTP (закомментировано)
      #- protocol: ntp
      #  ip: '1.pool.ntp.org'
      #  pollinterval: 4s
      #  monitor_only: false

      # Пример конфигурации PTP (закомментировано)
      #- protocol: ptp
      #  domain: 0
      #  serve_unicast: true
      #  serve_multicast: true
      #  server_only: false
      #  announce_interval: 1
      #  sync_interval: 0
      #  delayrequest_interval: 0
      #  disable: false
      #  unicast_master_table: ['192.168.1.100', '192.168.1.101']
      #  delay_strategy: e2e
      #  priority1: 128
      #  priority2: 128
      #  monitor_only: false
      #  use_layer2: false
      #  interface: eth0
      #  profile: 'enterprise'

    # Вторичные источники времени (активируются при отсутствии первичных)
    secondary_clocks:

      # Пример резервного NTP сервера
      - protocol: ntp
        ip: '2.pool.ntp.org'
        pollinterval: 4s
        monitor_only: false

      # Пример конфигурации NMEA (закомментировано)
      #- protocol: nmea
      #  device: '/dev/ttyS0'
      #  baud: 9600
      #  offset: 0
      #  monitor_only: false

  # Настройки тонкой настройки PTP
  ptp_tuning:

    # Включить глобальные PTP сокеты
    enable_ptp_global_sockets: false

    # Случайная задержка DELAY_REQ пакетов на 200-800мс
    relax_delay_requests: true

    # Автоматическое обнаружение PTP источников
    auto_discover_enabled: false

    # TTL для PTP multicast
    multicast_ttl: 1

    # DSCP настройки для PTP сообщений
    dscp:
      general: "af33"
      event: "ef"

    # Стандарт PTP
    ptp_standard: "1588-2008"

    # Качество часов
    clock_quality:
      auto: true
      class: 248
      accuracy: 0x23
      variance: 0xFFFF
      timesource: 0xA0

    # PHC настройки
    phc:
      tai_offset: auto

  # Синхронизация RTC
  synchronise_rtc:
    enable: true
    clock_interval: 11m

  # CLI интерфейс
  cli:
    enable: true
    bind_port: 65129
    bind_host: 127.0.0.1
    username: "admin"
    password: "password"

  # HTTP интерфейс
  http:
    enable: true
    bind_port: 8088
    bind_host: 127.0.0.1

  # Настройки логирования
  logging:
    # Размер буфера для записей при отключении от Elastic
    buffer_size: 10000

    # Вывод в stdout
    stdout:
      enable: true

    # Удаленный syslog
    syslog:
      enable: false
      host: remote.syslog-server.com
      port: 514

# ================================== General ===================================

# Имя отправителя
name: "shiwatime-host"

# Теги отправителя
tags: ["time-sync", "production"]

# Дополнительные поля
fields:
  env: production
  datacenter: dc1

# ================================= Dashboards =================================
setup:
  dashboards:
    enabled: false
    directory: /etc/shiwatime/kibana

  # ================================== ILM ===================================
  ilm:
    enabled: true
    policy_name: "shiwatime"
    check_exists: true

# ================================== Outputs ===================================

# Настройка вывода в Elasticsearch
output:
  elasticsearch:
    # Хосты Elasticsearch
    hosts: ['localhost:9200']
    
    # Протокол (http или https)
    protocol: 'http'
    
    # Аутентификация (необязательно)
    #username: 'elastic'
    #password: 'changeme'
    #api_key: 'id:api_key'
    
    # SSL настройки для безопасного соединения
    #ssl.certificate_authorities: ['/etc/shiwatime/pki/ca.crt']
    #ssl.certificate: '/etc/shiwatime/pki/shiwatime.crt'
    #ssl.key: '/etc/shiwatime/pki/shiwatime.key'
    #ssl.verification_mode: "certificate"